version: "3"
services:
  mongo:
    image: mongo:4.4.6
    restart: always
    container_name: "genieacs-mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/var/log/mongodb
    volumes:
      - data_db:/data/db
      - data_configdb:/data/configdb
    expose:
      - 27017

  genieacs:
    depends_on:
      - 'mongo'
    image: drumsergio/genieacs:1.2.13
    restart: always
    container_name: "genieacs"
    environment:
      - GENIEACS_UI_JWT_SECRET=changeme
      - GENIEACS_CWMP_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-cwmp-access.log
      - GENIEACS_NBI_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-nbi-access.log
      - GENIEACS_FS_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-fs-access.log
      - GENIEACS_UI_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-ui-access.log
      - GENIEACS_DEBUG_FILE=/var/log/genieacs/genieacs-debug.yaml
      - GENIEACS_EXT_DIR=/opt/genieacs/ext
      - GENIEACS_MONGODB_CONNECTION_URL=mongodb://mongo/genieacs
    ports:
      - "7547:7547"
      - "7557:7557"
      - "7567:7567"
      - "4000:3000"
    volumes:
      - ./pages:/opt/genieacs/pages
      - ./virtual-params:/opt/genieacs/virtual-parameters
      - ./provision-script:/opt/genieacs/provision
      - opt_volume:/opt

volumes:
  data_db:
  data_configdb:
  opt_volume:
